<main class="container customer-account d-flex flex-column justify-content-center">
    <form id="admin-login-form" action="/admin-connect-fg52csll3" method="POST">
        <fieldset class="container w-50 p-4 rounded d-flex flex-column flex-wrap">
            <legend class=" fs-3">Connexion</legend>
            <div class="mb-3">
                <label for="email">Email</label>
                <input value="<?php if (isset($email)) : ?>
                    <?= htmlspecialchars($email); ?> <?php endif; ?>" class="form-control" type="email" name="email" id="email">
            </div>
            <div class="mb-3">
                <label for="password">Mot de passe</label>
                <input value="<?php if (isset($password)) : ?><?= htmlspecialchars($password); ?><?php endif; ?>" class="form-control" type="password" name="password" id="password">
            </div>
            <?php if (isset($error['login'])) : ?>
                <p class="mt-1 alert alert-danger p-2"><?= htmlspecialchars($error['login']); ?></p>
            <?php endif; ?>
            <input class="btn btn-dark g-recaptcha" data-sitekey="6LcqsfonAAAAAAo0CGLPRTSvDOXRzxwBDQcSUh0X" data-callback="onSubmit" data-action='submit' type="submit" value="Connexion">
        </fieldset>
    </form>
</main>
<script>
    function onSubmit(token) {
        document.getElementById("admin-login-form").submit();
    }
</script>
</main>