<main class="container py-5 CGUV">
    <div class="text-center pb-4">
        <h2 class="">Conditions générales de vente et d'utilisation</h2>
    </div>

    <h3 class="mt-4 mb-3">Article 1 – Champ d’application</h3>
    <p>Les présentes Conditions Générales de Vente s’appliquent, sans restriction ni réserve à l’ensemble des ventes conclues par la Société FAYETT-VALLEY 61 RUE DE DIJON 21121 FONTAINE-LES-DIJON, immatriculée au RCS Dijon sous le numéro 507 436 715 et ayant comme numéro de TVA intra-communautaire FR 14 533 790 978 pour l’achat de biens par le Vendeur sur son site antredessaveurs.fr</p>
    <p>Ces conditions s’appliquent à l’exclusion de toutes autres conditions, et notamment celles applicables pour les ventes en magasin ou au moyen d’autres circuits de distribution et de commercialisation.</p>
    <p>Ces Conditions Générales de Vente sont accessibles à tout moment sur ce site Internet et prévaudront, le cas échéant, sur toute autre version ou tout autre document contradictoire.</p>
    <p>Sauf preuve contraire, les données enregistrées par la Société FAYETT-VALLEY constituent la preuve de l’ensemble des transactions.</p>
    <p>Les offres de produits s’entendent dans la limite des stocks disponibles. Les indications sur la disponibilité des produits sont fournies au moment de la passation de la commande.</p>
    <p>Les modifications de ces Conditions Générales de Vente sont opposables aux utilisateurs du site à compter de leur mise en ligne et ne peuvent s’appliquer aux transactions conclues antérieurement.</p>
    <p>La validation de la commande par l’acheteur vaut acceptation sans réserve des présentes Conditions Générales de Vente.</p>
    <p>Les fournisseurs peuvent changer sans préavis la composition technique des références produits. antredessaveurs.fr est à tout moment en droit de réactualiser, d’améliorer ses fiches ou de retirer de la vente ses produits. Il vous appartient, si vous ne vous estimez pas suffisamment compétent, de vous faire assister par un conseiller. Vous avez la possibilité de contacter antredessaveurs.fr pour obtenir les renseignements complémentaires sur les produits présentés via la page contact de notre site.</p>
    <p>Pour toute question relative à une commande en ligne, le service client de antredessaveurs.fr peut être joint :</p>
    <ul>
        <li>via la section <a href="/contact">« contact »</a></li>
        <li>par téléphone au 0X XX XX XX XX du lundi 15h - 19 h, du mardi au samedi 9h – 13h et 15h – 19h30 et le diamnche 9h - 13h et 16h 19h</li>
    </ul>
    <h3 class="mt-4 mb-3">Article 2 - Commande</h3>
    <p>Il appartient à l’acheteur de sélectionner les produits qu’il désire commander, selon les modalités suivantes :</p>
    <p><strong>2.1 – Identification</strong></p>
    <p>Lors de la première commande par Internet, tout nouveau client doit créer un « compte client » :</p>
    <ul>
        <li>Une adresse mail valide</li>
        <li>Un mot de passe d’au moins huit caractères</li>
    </ul>
    <p>Lors de chaque validation de commande, vous serez informé de votre numéro de commande afin de la regler et la réceptionner en magasin à l'adresse : 61 RUE DE DIJON 21121 FONTAINE-LES-DIJON.</p>
    <p>Le Client reconnaît être parfaitement informé du fait que son accord concernant le contenu des Conditions Générales de Vente ne nécessite pas de signature manuscrite, dans la mesure où le client commande en ligne les produits et services qui y sont présentés.</p>
    <p>Le « double clic » associé à la procédure d’authentification, de non-répudiation et de l’intégrité des messages constituent une signature électronique. Cette signature électronique a valeur de signature manuscrite entre les parties.</p>
    <p>La prise en compte de la commande est confirmée par l’envoi d’un email à l’adresse indiquée lors de la création du « compte client ».</p>
    <p>Les informations contractuelles sont présentées en langue française et feront l’objet d’une confirmation reprenant ces informations au plus tard au moment de la réception.</p>
    <p>antredessaveurs.fr se réserve le droit d’annuler ou de refuser toute commande d’un client avec lequel il existerait un litige relatif au paiement d’une commande antérieure.</p>
    <p><strong>2.2 – Validation de la commande</strong></p>
    <p>Toute commande validée par le Client entraîne l’acceptation des présentes Conditions Générales de Vente sans possibilité de recours sauf cas de rupture de stock ou de l’application du droit de rétractation.</p>
    <p>Chaque commande fera l’objet d’une confirmation par émail dans lequel sera récapitulé l’ensemble de la commande.</p>
    <p><strong>2.3 – Annulation de la commande</strong></p>
    <p>Toute demande d’annulation de la commande devra être adressée à antredessaveurs.fr via la rubrique <a href="/contact">« contact »</a></p>
    <p>Toute résiliation par le client d’une commande ou d’un contrat, en dehors des clauses prévues à cet effet, donne lieu à dommages et intérêts.</p>
    <h3 class="mt-4 mb-3">Article 3 – Tarifs</h3>
    <p><strong>3.1 – Généralités</strong></p>
    <p>Les produits sont fournis aux tarifs en vigueur figurant sur le site, lors de la validation de la commande par le Vendeur et sont exprimés en Euros.</p>
    <p>Seuls les tarifs affichés sur le site antredessaveurs.fr font foi.</p>
    <p>Ces tarifs sont fermes et non révisables pendant leur période de validité, telle qu’indiqué sur le site du Vendeur.</p>
    <p>Les tarifs comprennent la taxe sur la valeur ajoutée (T.V.A) applicable au jour de la commande et tout changement du taux applicable de la T.V.A sera automatiquement répercuté sur le prix des produits vendus sur le site antredessaveurs.fr.</p>
    <p><strong>3.2 – Facture</strong></p>
    <p>La facture est établie et distribué à chaque retrait de commande en magasin.</p>
    <p>Elle peut être disponible sous format numérique via la rebrique : <a href="/mon-compte">« mon compte »</a>. Il a la possibilité de la télécharger et/ou de l’imprimer.</p>
    <h3 class="mt-4 mb-3">Article 4 – Disponibilité</h3>
    <p>La disponibilité des articles vendus sur le site antredessaveurs.fr est indiquée sur les fiches d’information de chaque article.</p>
    <p>Les articles sont vendus dans la limite des stocks disponibles</p>
    <h3 class="mt-4 mb-3">Article 5 – Responsabilité du Vendeur – Garantie</h3>
    <p>Les produits fournis par le Vendeur bénéficient, conformément aux dispositions légales :</p>
    <ul>
        <li>de la garantie légale de conformité,</li>
        <li>de la garantie légale contre les vices cachés provenant d’un défaut de matière, de conception ou de fabrication affectant les produits livrés et les rendant impropres à l’utilisation,</li>
    </ul>
    <p>Toute garantie est exclue en cas de mauvaise utilisation, négligence ou défaut d’entretien de la part de l’Acheteur, comme en cas d’usure normale du bien, d’accident ou de force majeure et la garantie du Vendeur est limitée au remplacement ou au remboursement des produits non conformes ou affectés d’un vice.</p>
    <p>Les photographies et illustrations accompagnant les produits sur le site Internet n’ont pas la valeur contractuelle et ne sauraient donc engager la responsabilité du Vendeur.</p>
    <p>L’Acheteur est seul responsable du choix des produits, de leur conservation et de leur utilisation.</p>
    <p>Le vendeur ne sera pas considéré comme responsable ni défaillant pour tout retard ou inexécution consécutif à la survenance d’un cas de force majeure habituellement reconnu par la jurisprudence française.</p>
    <h3 class="mt-4 mb-3">Article 6 – Informatiques et Libertés</h3>
    <p>En application de la loi 78-17 « Informatique et libertés » du 6 janvier 1978 modifiée par la loi du 6 août 2004, il est rappelé que les données nominatives qui sont demandées à l’Acheteur sont nécessaires au traitement de sa commande et à l’établissement des factures, notamment.</p>
    <p>Le traitement des informations communiquées par l’intermédiaire du site du Vendeur a fait l’objet d’une déclaration auprès de la CNIL.</p>
    <p><strong>Utilisation et transmission de vos données personnelles</strong></p>
    <p>Le traitement automatisé de vos données personnelles a pour finalité le traitement de votre commande, de vos abonnements à nos Newsletters, et plus généralement la gestion de la relation clientèle. Les informations reste uniquement sur notre base et ne sont pas divulgés a d’autre service Vos données personnelles nous permettent de réaliser toute étude ou analyse correspondante, notamment en fonction des achats que vous effectuez sur notre site, pour répondre au mieux à vos besoins.</p>
    <p><strong>Droit d’accès, de modification, d’opposition</strong></p>
    <p>L’Acheteur dispose, conformément aux réglementations nationales et européennes en vigueur d’un droit d’accès permanent, de modification, de rectification et d’opposition s’agissant des informations les concernant en écrivant à l’adresser suivante : L'Antre des saveurs - service client - 61 RUE DE DIJON 21121 FONTAINE-LES-DIJON, en indiquant vos nom, prénom, email et adresse. Conformément à la réglementation en vigueur, votre demande doit être signée et accompagnée d’un titre d’identité portant votre signature et préciser l’adresse à laquelle doit vous parvenir la réponse. Une réponse vous sera adressée dans un délai d’un moi suivant la réception de la demande.</p>
    <h3 class="mt-4 mb-3">Article 7 – Propriété intellectuelle</h3>
    <p>Le contenu du site est la propriété du Vendeur et est protégé par les lois françaises et internationales relatives à la propriété intellectuelle.</p>
    <p>Toute reproduction totale ou partielle de ce contenu est strictement interdite et est susceptible de constituer un délit de contrefaçon ; Notamment des logos, des marques enregistrées, des textes, des photographies, des images constituent des œuvres protégés par des droits de propriété intellectuelle ou des droits de la personne.</p>
    <p>En outre, le Prestataire reste propriétaire de tous les droits de propriété intellectuelle sur les études, dessins, modèles, prototypes, etc, réalisés (même à la demande du Client) en vue de la fourniture des services du Client. Le Client s’interdit donc toute reproduction ou exploitation desdites études, dessins, modèles et prototypes, etc, sans l’autorisation expresse, écrite et préalable du Prestataire qui peut la conditionner à une contrepartie financière.</p>
    <h3 class="mt-4 mb-3">Article 8 – Droit applicable – Langue</h3>
    <p>De convention expresse entre les parties, le présent contrat est régi et soumis au droit français.</p>
    <p>Il est rédigé en langue française. Dans le cas où il serait traduit en une ou plusieurs langues, seul le texte français ferait foi en cas de litige.</p>
    <p>Le présent contrat est régi par la loi française. L’application de la Convention de Vienne sur l’attribution internationale de marchandises est expressément écartée.</p>
    <p>L'Antre des Saveurs archivera les bons de commandes et les factures sur un support fiable et durable constituant une copie fidèle conformément aux dispositions de l’article 1348 du Code civil. Les registres informatisés de antredessaveurs.fr seront considérés par les parties comme preuve des communications et commandes intervenus entre les parties, sauf preuve contraire. La signature électronique constituée par la procédure de “double-clic” lors de la passation de la commande et de son enregistrement a valeur manuscrite entre les parties. La loi française est applicable sans pour autant écarter l’application les droits législatifs impératifs accordés aux consommateurs ou d’une loi impérative plus protectrice par le juge étranger saisi par un consommateur du pays correspondant.</p>
    <p>Tous différents relatifs à la formation, l’exécution et la cessation des obligations contractuelles entre les parties ne pouvant donner lieu à un règlement à l’amiable seront soumis aux tribunaux français. En cas de litige avec des professionnels et/ou commerçants, celui-ci sera soumis à la juridiction du Tribunal de Commerce de Dijon dans le ressort duquel se trouve le siège de L'Antre des Saveurs, quels que soient les conditions de vente et le mode de paiement accepté, même en cas d’appel en garantie ou de pluralité des défendeurs, L'Antre des Saveurs se réservant le droit de saisir le Tribunal territorialement compétent dont relève le siège de l’acheteur. Il est rappelé que les présentes dispositions ne privent pas les clients habitant hors de France des règles prévues dans les conventions internationales qui leur sont applicables.</p>
    <p>Si une ou plusieurs stipulations des présentes conditions générales de vente sont tenues pour non valides ou déclarées comme telles en application d’une loi, d’un règlement ou à la suite d’une décision définitive d’une juridiction compétente, les autres stipulations garderont toute leur force et leur portée.</p>
    <p>Le fait pour l’une des parties de ne pas se prévaloir d’un manquement auprès de l’autre partie à l’une quelconque des obligations visées au sein des présentes conditions générales de vente ne saurait être interprété pour l’avenir comme une renonciation à l’obligation en cause.</p>
    <h3 class="mt-4 mb-3">Article 9 – Litiges</h3>
    <p>Conformément à l’article L.133-4 du Code de la Consommation, en cas de contestation, le client peut recourir à une procédure de médiation conventionnelle ou à tout autre mode alternatif de règlement des différends.</p>
    <p>A défaut d’un tel choix, le client peut également saisir les juridictions compétentes.</p>
    <h3 class="mt-4 mb-3">Article 10 – Acceptation de l’Acheteur</h3>
    <p>Le fait pour une personne physique ou morale, de commander sur le site Internet du Vendeur emporte adhésion et acceptation pleine et entière des présentes Conditions générales de Vente, ce qui est expressément reconnu par l’Acheteur, qui renonce, notamment à se prévaloir de tout document contradictoire, qui serait inopposable au vendeur.</p>
</main>