<main class="pb-5">
    <div class="text-center pb-4">
        <h2 class="">Connexion</h2>
    </div>

    <form id="login-form" action="/login" method="POST">
        <fieldset class="container w-50 p-4 rounded d-flex flex-column flex-wrap">
            <legend class=" fs-3">Connexion</legend>
            <div class="mb-3">
                <label for="email">Email</label>
                <input value="<?php if (isset($email)) : ?>
                    <?= htmlspecialchars($email); ?> <?php endif; ?>" class="form-control" type="email" name="email" id="email">
            </div>
            <div class="mb-3">
                <label for="password">Mot de passe</label>
                <input value="<?php if (isset($password)) : ?><?= htmlspecialchars($password); ?><?php endif; ?>" class="form-control" type="password" name="password" id="password">
            </div>
            <?php if (isset($error['login'])) : ?>
                <p class="mt-1 alert alert-danger p-2"><?= htmlspecialchars($error['login']); ?></p>
            <?php endif; ?>
            <input class="btn btn-dark g-recaptcha" data-sitekey="6LcqsfonAAAAAAo0CGLPRTSvDOXRzxwBDQcSUh0X" data-callback="onSubmit" data-action='submit' type="submit" value="Connexion">

            <legend class="pt-4 text-center fs-3">Vous n'avez pas encore de compte ?</legend>
            <a href="/signup" class="btn btn-dark">Créer un compte</a>
        </fieldset>
    </form>
</main>
<script>
    function onSubmit(token) {
        document.getElementById("login-form").submit();
    }
</script>