<main class="container py-5 privacy-policy">
    <div class="text-center pb-4">
        <h2 class="">Politique de confidentialité</h2>
    </div>
    <h3>Qui sommes-nous ?</h3>
    <p>L'adresse de notre site Web est : <a href="/">https://www.antredessaveurs.fr</a>.</p>
    <h3>Utilisation des données personnelles collectées</h3>
    <h4>Commentaires</h4>
    <p>Quand vous laissez un commentaire sur notre site web, les données inscrites dans le formulaire de commentaire, mais aussi votre adresse IP et l'agent utilisateur de votre navigateur sont collectés pour nous aider à la détection des commentaires indésirables.</p>
    <p>Une chaîne anonymisée créée à partir de votre adresse de messagerie (également appelée hash) peut être envoyée au service Gravatar pour vérifier si vous utilisez ce dernier. Les clauses de confidentialité du service Gravatar sont disponibles ici : <a href="https://automattic.com/privacy/">https://automattic.com/privacy/</a>. Après validation de votre commentaire, votre photo de profil sera visible publiquement à coté de votre commentaire.</p>
    <h4>Médias</h4>
    <p>Si vous êtes un utilisateur ou une utilisatrice enregistré·e et que vous téléversez des images sur le site web, nous vous conseillons d'éviter de téléverser des images contenant des données EXIF de coordonnées GPS. Les visiteurs de votre site web peuvent télécharger et extraire des données de localisation depuis ces images.</p>
    <h4>Formulaires de contact</h4>
    <p>Le formulaire de contact, ainsi que tous les autres formulaires ou téléservices limitent la collecte des données personnelles au strict nécessaire et indiquent clairement :</p>
    <ul>
        <li>l'objectif du recueil de ces données (finalité) ;</li>
        <li>si ces données sont obligatoires ou facultatives pour la gestion de votre demande ;</li>
        <li>qui pourra en prendre connaissance (uniquement notre société en principe, sauf précision contraire dans le formulaire de saisie lorsqu'une transmission à un tiers est strictement nécessaire pour la gestion de votre demande) ;</li>
        <li>vos droits « Informatique et Libertés » (droits d'accès, d'opposition et de rectification) et la façon de les exercer auprès de notre société.</li>
        <li>par courrier signé accompagné de la copie d'un titre d'identité à l'adresse de la société.</li>
    </ul>
    <p>Les données personnelles recueillies dans le cadre des services proposés sur le site Web La Maison De Judith sont transmises et conservées selon des protocoles sécurisés ; elles ne sont pas conservées au-delà de la durée nécessaire.</p>
    <p>Pour toute information à ce sujet ou exercice de vos droits Informatique et Libertés, vous pouvez contacter son Délégué à la Protection des Données (DPO).</p>
    <h4>Cookies</h4>
    <p>Si vous déposez un commentaire sur notre site, il vous sera proposé d'enregistrer votre nom, adresse de messagerie et site web dans des cookies. C'est uniquement pour votre confort afin de ne pas avoir à saisir ces informations si vous déposez un autre commentaire plus tard. Ces cookies expirent au bout d'un an.</p>
    <p>Si vous vous rendez sur la page de connexion, un cookie temporaire sera créé afin de déterminer si votre navigateur accepte les cookies. Il ne contient pas de données personnelles et sera supprimé automatiquement à la fermeture de votre navigateur.</p>
    <p>Lorsque vous vous connecterez, nous mettrons en place un certain nombre de cookies pour enregistrer vos informations de connexion et vos préférences d'écran. La durée de vie d'un cookie de connexion est de deux jours, celle d'un cookie d'option d'écran est d'un an. Si vous cochez « Se souvenir de moi », votre cookie de connexion sera conservé pendant deux semaines. Si vous vous déconnectez de votre compte, le cookie de connexion sera effacé.</p>
    <p>En modifiant ou en publiant une publication, un cookie supplémentaire sera enregistré dans votre navigateur. Ce cookie ne comprend aucune donnée personnelle. Il indique simplement l'ID de la publication que vous venez de modifier. Il expire au bout d'un jour.</p>
    <h4>Contenu embarqué depuis d'autres sites</h4>
    <p>Les articles de ce site peuvent inclure des contenus intégrés (par exemple des vidéos, images, articles…). Le contenu intégré depuis d'autres sites se comporte de la même manière que si le visiteur se rendait sur cet autre site.</p>
    <p>Ces sites web pourraient collecter des données sur vous, utiliser des cookies, embarquer des outils de suivis tiers, suivre vos interactions avec ces contenus embarqués si vous disposez d'un compte connecté sur leur site web.</p>
    <h4>Statistiques et mesures d'audience</h4>
    <p>En vue d'adapter le site aux demandes de ses visiteurs, nous mesurons le nombre de visites, le nombre de pages vues ainsi que l'activité des visiteurs sur le site et leur fréquence de retour.</p>
    <p>Nous collectons également votre adresse IP, afin de déterminer la ville depuis laquelle vous vous connectez. Celle-ci est immédiatement anonymisée après utilisation. Notre société ne peut donc en aucun cas remonter par ce biais à une personne physique.</p>
    <p>Les données personnelles recueillies par le biais du cookie sont conservées par notre société pour une durée de 13 mois maximum. Elles ne sont pas cédées à des tiers ni utilisées à d'autres fins.</p>
    <h3>Utilisation et transmission de vos données personnelles</h3>
    <h4>Durées de stockage de vos données</h4>
    <p>Si vous laissez un commentaire, le commentaire et ses métadonnées sont conservés indéfiniment. Cela permet de reconnaître et approuver automatiquement les commentaires suivants au lieu de les laisser dans la file de modération.</p>
    <p>Pour les utilisateurs et utilisatrices qui s'enregistrent sur notre site (si cela est possible), nous stockons également les données personnelles indiquées dans leur profil. Tous les utilisateurs et utilisatrices peuvent voir, modifier ou supprimer leurs informations personnelles à tout moment (à l'exception de leur nom d'utilisateur·ice). Les gestionnaires du site peuvent aussi voir et modifier ces informations.</p>
    <h4>Les droits que vous avez sur vos données</h4>
    <p>Si vous avez un compte ou si vous avez laissé des commentaires sur le site, vous pouvez demander à recevoir un fichier contenant toutes les données personnelles que nous possédons à votre sujet, incluant celles que vous nous avez fournies. Vous pouvez également demander la suppression des données personnelles vous concernant. Cela ne prend pas en compte les données stockées à des fins administratives, légales ou pour des raisons de sécurité.</p>
    <h4>Transmission de vos données personnelles</h4>
    <p>Les commentaires des visiteurs peuvent être vérifiés à l'aide d'un service automatisé de détection des commentaires indésirables.</p>
    <h4>Informations de contact</h4>
    <p class="pp-address">
        <strong>L'Antre des Saveurs</strong>
        <br>
        61 RUE DE DIJON
        <br>
        21121 FONTAINE-LES-DIJON
        <br>
        <a href="mailto:contact@antredessaveurs.fr" class="text-dark text-decoration-underline"><span>contact@antredessaveurs.fr</span></a>
    </p>
</main>